### ISSUE TITLE
[Milestone 1] Develop website concept

### ISSUE THREAD

**Issue by marbarrantescepas** [marbarrantescepas/OS-neuroscience#2]
- [ ] Define general structure of the website 
- [ ] Find a template to start working on (GitHub pages)
- [ ] Add contribute.md, etc. 
- [ ] ...

**Comment by multinetlab** [comment]
would be cool to add our awards to the first page as well, (or somewhere)
